version: '3.1'

services:

    database:
        image: "postgres:12.1-alpine"
        restart: always
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: soukosync_prod

          
    soukosync:
        build:
            context: .
        environment:
            TOKEN: ${TOKEN}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DATABASE_URL: ${DATABASE_URL}
            SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        ports:
            - 80:80
    