version: '3.1'

services:

    database:
        image: "postgres:12.1-alpine"
        restart: always
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: soukosync_prod

          
    soukosync:
        build:
            context: .
        environment:
            API_TOKEN: ${API_TOKEN}
            API_USER: ${API_USER}
            API_PASSWORD: ${API_PASSWORD}
            INTERVAL_SCHEDULER_SECONDS: ${INTERVAL_SCHEDULER_SECONDS}
            INTERVAL_RETRY_TOKEN_SECONDS: ${INTERVAL_RETRY_TOKEN_SECONDS}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DATABASE_URL: "ecto://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/soukosync_prod"
            SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        ports:
            - 80:80
    